// Code generated by download. DO NOT EDIT.

package iso20022_auth_036_001_02

import (
	"bytes"
	"encoding/xml"
	"time"
)

type ActiveCurrencyAnd13DecimalAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

type AgriculturalCommodityDairy1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType20Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type AgriculturalCommodityForestry1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType21Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type AgriculturalCommodityGrain1 struct {
	BasePdct     AssetClassProductType1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType5Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType15Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type AgriculturalCommodityLiveStock1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType22Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type AgriculturalCommodityOilSeed1 struct {
	BasePdct     AssetClassProductType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct"`
}

type AgriculturalCommodityOliveOil1 struct {
	BasePdct     AssetClassProductType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType3Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType4Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type AgriculturalCommodityPotato1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType45Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type AgriculturalCommoditySeafood1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType23Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type AgriculturalCommoditySoft1 struct {
	BasePdct     AssetClassProductType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType2Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct"`
}

type AmountAndDirection61 struct {
	Amt ActiveCurrencyAnd13DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Amt"`
	Sgn bool                             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Sgn,omitempty"`
}

type AssetClass2 struct {
	Cmmdty DerivativeCommodity2       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Cmmdty,omitempty"`
	Intrst DerivativeInterest3        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Intrst,omitempty"`
	FX     DerivativeForeignExchange3 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FX,omitempty"`
}

type AssetClassCommodity3Choice struct {
	Agrcltrl          AssetClassCommodityAgricultural1Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Agrcltrl,omitempty"`
	Nrgy              AssetClassCommodityEnergy1Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Nrgy,omitempty"`
	Envttl            AssetClassCommodityEnvironmental1Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Envttl,omitempty"`
	Frtlzr            AssetClassCommodityFertilizer1Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Frtlzr,omitempty"`
	Frght             AssetClassCommodityFreight1Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Frght,omitempty"`
	IndstrlPdct       AssetClassCommodityIndustrialProduct1Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IndstrlPdct,omitempty"`
	Metl              AssetClassCommodityMetal1Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Metl,omitempty"`
	OthrC10           AssetClassCommodityOtherC102Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OthrC10,omitempty"`
	Ppr               AssetClassCommodityPaper1Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Ppr,omitempty"`
	Plprpln           AssetClassCommodityPolypropylene1Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Plprpln,omitempty"`
	Infltn            AssetClassCommodityInflation1                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Infltn,omitempty"`
	MultiCmmdtyExtc   AssetClassCommodityMultiCommodityExotic1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 MultiCmmdtyExtc,omitempty"`
	OffclEcnmcSttstcs AssetClassCommodityOfficialEconomicStatistics1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OffclEcnmcSttstcs,omitempty"`
	Othr              AssetClassCommodityOther1                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Othr,omitempty"`
}

type AssetClassCommodityAgricultural1Choice struct {
	GrnOilSeed AgriculturalCommodityOilSeed1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 GrnOilSeed,omitempty"`
	Soft       AgriculturalCommoditySoft1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Soft,omitempty"`
	Ptt        AgriculturalCommodityPotato1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Ptt,omitempty"`
	OlvOil     AgriculturalCommodityOliveOil1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OlvOil,omitempty"`
	Dairy      AgriculturalCommodityDairy1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Dairy,omitempty"`
	Frstry     AgriculturalCommodityForestry1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Frstry,omitempty"`
	Sfd        AgriculturalCommoditySeafood1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Sfd,omitempty"`
	LiveStock  AgriculturalCommodityLiveStock1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 LiveStock,omitempty"`
	Grn        AgriculturalCommodityGrain1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Grn,omitempty"`
}

type AssetClassCommodityEnergy1Choice struct {
	Elctrcty  EnergyCommodityElectricity1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Elctrcty,omitempty"`
	NtrlGas   EnergyCommodityNaturalGas1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NtrlGas,omitempty"`
	Oil       EnergyCommodityOil1             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Oil,omitempty"`
	Coal      EnergyCommodityCoal1            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Coal,omitempty"`
	IntrNrgy  EnergyCommodityInterEnergy1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IntrNrgy,omitempty"`
	RnwblNrgy EnergyCommodityRenewableEnergy1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RnwblNrgy,omitempty"`
	LghtEnd   EnergyCommodityLightEnd1        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 LghtEnd,omitempty"`
	Dstllts   EnergyCommodityDistillates1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Dstllts,omitempty"`
}

type AssetClassCommodityEnvironmental1Choice struct {
	Emssns   EnvironmentalCommodityEmission1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Emssns,omitempty"`
	Wthr     EnvironmentalCommodityWeather1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Wthr,omitempty"`
	CrbnRltd EnvironmentalCommodityCarbonRelated1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 CrbnRltd,omitempty"`
}

type AssetClassCommodityFertilizer1Choice struct {
	Ammn             FertilizerCommodityAmmonia1                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Ammn,omitempty"`
	DmmnmPhspht      FertilizerCommodityDiammoniumPhosphate1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 DmmnmPhspht,omitempty"`
	Ptsh             FertilizerCommodityPotash1                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Ptsh,omitempty"`
	Slphr            FertilizerCommoditySulphur1                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Slphr,omitempty"`
	Urea             FertilizerCommodityUrea1                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Urea,omitempty"`
	UreaAndAmmnmNtrt FertilizerCommodityUreaAndAmmoniumNitrate1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 UreaAndAmmnmNtrt,omitempty"`
}

type AssetClassCommodityFreight1Choice struct {
	Dry       FreightCommodityDry1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Dry,omitempty"`
	Wet       FreightCommodityWet1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Wet,omitempty"`
	CntnrShip FreightCommodityContainerShip1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 CntnrShip,omitempty"`
}

type AssetClassCommodityIndustrialProduct1Choice struct {
	Cnstrctn IndustrialProductCommodityConstruction1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Cnstrctn,omitempty"`
	Manfctg  IndustrialProductCommodityManufacturing1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Manfctg,omitempty"`
}

type AssetClassCommodityInflation1 struct {
	BasePdct AssetClassProductType12Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
}

type AssetClassCommodityMetal1Choice struct {
	NonPrcs MetalCommodityNonPrecious1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NonPrcs,omitempty"`
	Prcs    MetalCommodityPrecious1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Prcs,omitempty"`
}

type AssetClassCommodityMultiCommodityExotic1 struct {
	BasePdct AssetClassProductType13Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
}

type AssetClassCommodityOfficialEconomicStatistics1 struct {
	BasePdct AssetClassProductType14Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
}

type AssetClassCommodityOther1 struct {
	BasePdct AssetClassProductType15Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
}

type AssetClassCommodityOtherC102Choice struct {
	Dlvrbl    OtherC10CommodityDeliverable2    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Dlvrbl,omitempty"`
	NonDlvrbl OtherC10CommodityNonDeliverable2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NonDlvrbl,omitempty"`
}

type AssetClassCommodityPaper1Choice struct {
	CntnrBrd PaperCommodityContainerBoard1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 CntnrBrd,omitempty"`
	Nwsprnt  PaperCommodityNewsprint1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Nwsprnt,omitempty"`
	Pulp     PaperCommodityPulp1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Pulp,omitempty"`
	RcvrdPpr PaperCommodityRecoveredPaper1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RcvrdPpr,omitempty"`
}

type AssetClassCommodityPolypropylene1Choice struct {
	Plstc PolypropyleneCommodityPlastic1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Plstc,omitempty"`
}

// May be one of ALUM, ALUA, CBLT, COPR, IRON, MOLY, NASC, NICK, STEL, TINN, ZINC, OTHR, LEAD
type AssetClassDetailedSubProductType10Code string

// May be one of GOLD, OTHR, PLDM, PTNM, SLVR
type AssetClassDetailedSubProductType11Code string

// May be one of TNKR
type AssetClassDetailedSubProductType12Code string

// May be one of DBCR
type AssetClassDetailedSubProductType14Code string

// May be one of MWHT
type AssetClassDetailedSubProductType15Code string

// May be one of FWHT, SOYB, RPSD, OTHR, CORN, RICE
type AssetClassDetailedSubProductType1Code string

// May be one of ROBU, CCOA, BRWN, WHSG, OTHR
type AssetClassDetailedSubProductType2Code string

// May be one of LAMP
type AssetClassDetailedSubProductType4Code string

// May be one of BSLD, FITR, PKLD, OFFP, OTHR
type AssetClassDetailedSubProductType5Code string

// May be one of GASP, LNGG, NCGG, TTFG, NBPG
type AssetClassDetailedSubProductType6Code string

// May be one of BAKK, BDSL, BRNT, BRNX, CNDA, COND, DSEL, DUBA, ESPO, ETHA, FUEL, FOIL, GOIL, GSLN, HEAT, JTFL, KERO, LLSO, MARS, NAPH, NGLO, TAPI, WTIO, URAL
type AssetClassDetailedSubProductType7Code string

// May be one of CERE, ERUE, EUAE, EUAA, OTHR
type AssetClassDetailedSubProductType8Code string

// May be one of OTHC
type AssetClassProductType11Code string

// May be one of INFL
type AssetClassProductType12Code string

// May be one of MCEX
type AssetClassProductType13Code string

// May be one of OEST
type AssetClassProductType14Code string

// May be one of OTHR
type AssetClassProductType15Code string

// May be one of AGRI
type AssetClassProductType1Code string

// May be one of NRGY
type AssetClassProductType2Code string

// May be one of ENVR
type AssetClassProductType3Code string

// May be one of FRGT
type AssetClassProductType4Code string

// May be one of FRTL
type AssetClassProductType5Code string

// May be one of INDP
type AssetClassProductType6Code string

// May be one of METL
type AssetClassProductType7Code string

// May be one of PAPR
type AssetClassProductType8Code string

// May be one of POLY
type AssetClassProductType9Code string

// May be one of EMIS
type AssetClassSubProductType10Code string

// May be one of NPRM
type AssetClassSubProductType15Code string

// May be one of PRME
type AssetClassSubProductType16Code string

// May be one of PLST
type AssetClassSubProductType18Code string

// May be one of GROS
type AssetClassSubProductType1Code string

// May be one of DIRY
type AssetClassSubProductType20Code string

// May be one of FRST
type AssetClassSubProductType21Code string

// May be one of LSTK
type AssetClassSubProductType22Code string

// May be one of SEAF
type AssetClassSubProductType23Code string

// May be one of COAL
type AssetClassSubProductType24Code string

// May be one of DIST
type AssetClassSubProductType25Code string

// May be one of INRG
type AssetClassSubProductType26Code string

// May be one of LGHT
type AssetClassSubProductType27Code string

// May be one of RNNG
type AssetClassSubProductType28Code string

// May be one of CRBR
type AssetClassSubProductType29Code string

// May be one of SOFT
type AssetClassSubProductType2Code string

// May be one of WTHR
type AssetClassSubProductType30Code string

// May be one of DRYF
type AssetClassSubProductType31Code string

// May be one of WETF
type AssetClassSubProductType32Code string

// May be one of CSTR
type AssetClassSubProductType33Code string

// May be one of MFTG
type AssetClassSubProductType34Code string

// May be one of CBRD
type AssetClassSubProductType35Code string

// May be one of NSPT
type AssetClassSubProductType36Code string

// May be one of PULP
type AssetClassSubProductType37Code string

// May be one of RCVP
type AssetClassSubProductType38Code string

// May be one of AMMO
type AssetClassSubProductType39Code string

// May be one of OOLI
type AssetClassSubProductType3Code string

// May be one of DAPH
type AssetClassSubProductType40Code string

// May be one of PTSH
type AssetClassSubProductType41Code string

// May be one of SLPH
type AssetClassSubProductType42Code string

// May be one of UREA
type AssetClassSubProductType43Code string

// May be one of UAAN
type AssetClassSubProductType44Code string

// May be one of POTA
type AssetClassSubProductType45Code string

// May be one of CSHP
type AssetClassSubProductType46Code string

// May be one of DLVR
type AssetClassSubProductType47Code string

// May be one of NDLV
type AssetClassSubProductType48Code string

// May be one of GRIN
type AssetClassSubProductType5Code string

// May be one of ELEC
type AssetClassSubProductType6Code string

// May be one of NGAS
type AssetClassSubProductType7Code string

// May be one of OILP
type AssetClassSubProductType8Code string

// May be one of CRCK, DIFF, FUTR, MINI, OPTN, OTCT, ORIT, SWAP, TAPO, OTHR
type AssetClassTransactionType1Code string

// May be one of FXCR, FXEM, FXMJ
type AssetFXSubProductType1Code string

// May be one of ARGM, BLTC, EXOF, GBCL, IHSM, OTHR, PLAT
type AssetPriceType1Code string

// May be one of WIBO, TREA, TIBO, TLBO, SWAP, STBO, PRBO, PFAN, NIBO, MAAA, MOSP, LIBO, LIBI, JIBA, ISDA, GCFR, FUSW, EUCH, EUUS, EURI, EONS, EONA, CIBO, CDOR, BUBO, BBSW
type BenchmarkCurveName2Code string

type BenchmarkCurveName5Choice struct {
	Indx BenchmarkCurveName2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Indx,omitempty"`
	Nm   Max25Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Nm,omitempty"`
}

type BenchmarkCurveName6Choice struct {
	ISIN ISINOct2015Identifier   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ISIN,omitempty"`
	Indx BenchmarkCurveName2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Indx,omitempty"`
	Nm   Max25Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Nm,omitempty"`
}

// Must match the pattern [A-Z]{6,6}
type CFIOct2015Identifier string

// Must match the pattern [A-Z]{2,2}
type CountryCode string

type DebtInstrument2 struct {
	TtlIssdNmnlAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TtlIssdNmnlAmt"`
	MtrtyDt        ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 MtrtyDt,omitempty"`
	NmnlValPerUnit ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NmnlValPerUnit"`
	IntrstRate     InterestRate6Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IntrstRate"`
	DebtSnrty      DebtInstrumentSeniorityType1Code  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 DebtSnrty,omitempty"`
}

// May be one of SBOD, SNDB, MZZD, JUND
type DebtInstrumentSeniorityType1Code string

type DerivativeCommodity2 struct {
	Pdct      AssetClassCommodity3Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Pdct"`
	TxTp      AssetClassTransactionType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TxTp,omitempty"`
	FnlPricTp AssetPriceType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FnlPricTp,omitempty"`
}

type DerivativeForeignExchange3 struct {
	FxTp        AssetFXSubProductType1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FxTp,omitempty"`
	OthrNtnlCcy ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OthrNtnlCcy,omitempty"`
}

type DerivativeInstrument5 struct {
	XpryDt               ISODate                                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 XpryDt,omitempty"`
	PricMltplr           float64                                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 PricMltplr,omitempty"`
	UndrlygInstrm        FinancialInstrumentIdentification5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 UndrlygInstrm,omitempty"`
	OptnTp               OptionType2Code                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OptnTp,omitempty"`
	StrkPric             SecuritiesTransactionPrice4Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 StrkPric,omitempty"`
	OptnExrcStyle        OptionStyle7Code                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OptnExrcStyle,omitempty"`
	DlvryTp              PhysicalTransferType4Code                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 DlvryTp,omitempty"`
	AsstClssSpcfcAttrbts AssetClass2                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AsstClssSpcfcAttrbts,omitempty"`
}

type DerivativeInterest3 struct {
	IntrstRate        FloatingInterestRate8        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IntrstRate"`
	FrstLegIntrstRate InterestRate8Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FrstLegIntrstRate,omitempty"`
	OthrNtnlCcy       ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OthrNtnlCcy,omitempty"`
	OthrLegIntrstRate InterestRate8Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 OthrLegIntrstRate,omitempty"`
}

type Document struct {
	FinInstrmRptgRefDataDltaRpt FinancialInstrumentReportingReferenceDataDeltaReportV02 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FinInstrmRptgRefDataDltaRpt"`
}

type EnergyCommodityCoal1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType24Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnergyCommodityDistillates1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType25Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnergyCommodityElectricity1 struct {
	BasePdct     AssetClassProductType2Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType6Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType5Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct"`
}

type EnergyCommodityInterEnergy1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType26Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnergyCommodityLightEnd1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType27Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnergyCommodityNaturalGas1 struct {
	BasePdct     AssetClassProductType2Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType7Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType6Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type EnergyCommodityOil1 struct {
	BasePdct     AssetClassProductType2Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType8Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType7Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type EnergyCommodityRenewableEnergy1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType28Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnvironmentalCommodityCarbonRelated1 struct {
	BasePdct AssetClassProductType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType29Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type EnvironmentalCommodityEmission1 struct {
	BasePdct     AssetClassProductType3Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType10Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType8Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type EnvironmentalCommodityWeather1 struct {
	BasePdct AssetClassProductType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType30Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommodityAmmonia1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType39Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommodityDiammoniumPhosphate1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType40Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommodityPotash1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType41Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommoditySulphur1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType42Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommodityUrea1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType43Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FertilizerCommodityUreaAndAmmoniumNitrate1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType44Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FinancialInstrument48Choice struct {
	ISIN ISINOct2015Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ISIN,omitempty"`
	LEI  LEIIdentifier         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 LEI,omitempty"`
	Indx FinancialInstrument58 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Indx,omitempty"`
}

type FinancialInstrument53 struct {
	ISIN []ISINOct2015Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ISIN,omitempty"`
	LEI  []LEIIdentifier         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 LEI,omitempty"`
}

type FinancialInstrument58 struct {
	ISIN ISINOct2015Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ISIN,omitempty"`
	Nm   FloatingInterestRate8 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Nm"`
}

type FinancialInstrumentIdentification5Choice struct {
	Sngl FinancialInstrument48Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Sngl,omitempty"`
	Bskt FinancialInstrument53       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Bskt,omitempty"`
}

type FinancialInstrumentReportingReferenceDataDeltaReportV02 struct {
	RptHdr      SecuritiesMarketReportHeader1                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RptHdr"`
	FinInstrm   []SecuritiesReferenceDeltaStatusReport3Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FinInstrm,omitempty"`
	SplmtryData []SupplementaryData1                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SplmtryData,omitempty"`
}

type FloatingInterestRate6 struct {
	RefRate    BenchmarkCurveName6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RefRate"`
	Term       InterestRateContractTerm2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Term"`
	BsisPtSprd float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BsisPtSprd"`
}

type FloatingInterestRate8 struct {
	RefRate BenchmarkCurveName5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RefRate"`
	Term    InterestRateContractTerm2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Term,omitempty"`
}

type FreightCommodityContainerShip1 struct {
	BasePdct AssetClassProductType4Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType46Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
}

type FreightCommodityDry1 struct {
	BasePdct     AssetClassProductType4Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType31Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType14Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

type FreightCommodityWet1 struct {
	BasePdct     AssetClassProductType4Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType32Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType12Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IndustrialProductCommodityConstruction1 struct {
	BasePdct AssetClassProductType6Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType33Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type IndustrialProductCommodityManufacturing1 struct {
	BasePdct AssetClassProductType6Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType34Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type InterestRate6Choice struct {
	Fxd  float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Fxd,omitempty"`
	Fltg FloatingInterestRate6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Fltg,omitempty"`
}

type InterestRate8Choice struct {
	Fxd  float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Fxd,omitempty"`
	Fltg FloatingInterestRate8 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Fltg,omitempty"`
}

type InterestRateContractTerm2 struct {
	Unit RateBasis1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Unit"`
	Val  float64        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Val"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// Must match the pattern [A-Z0-9]{4,4}
type MICIdentifier string

// May be no more than 25 items long
type Max25Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 50 items long
type Max50Text string

type MetalCommodityNonPrecious1 struct {
	BasePdct     AssetClassProductType7Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType15Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType10Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct"`
}

type MetalCommodityPrecious1 struct {
	BasePdct     AssetClassProductType7Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType16Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType11Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AddtlSubPdct"`
}

// May be one of AMER, ASIA, BERM, EURO, OTHR
type OptionStyle7Code string

// May be one of CALL, PUTO, OTHR
type OptionType2Code string

type OtherC10CommodityDeliverable2 struct {
	BasePdct AssetClassProductType11Code    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType47Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type OtherC10CommodityNonDeliverable2 struct {
	BasePdct AssetClassProductType11Code    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType48Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type PaperCommodityContainerBoard1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType35Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type PaperCommodityNewsprint1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType36Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type PaperCommodityPulp1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType37Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type PaperCommodityRecoveredPaper1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType38Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

type Period2 struct {
	FrDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FrDt"`
	ToDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ToDt"`
}

type Period4Choice struct {
	Dt       ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Dt,omitempty"`
	FrDt     ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FrDt,omitempty"`
	ToDt     ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ToDt,omitempty"`
	FrDtToDt Period2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FrDtToDt,omitempty"`
}

// May be one of PHYS, OPTL, CASH
type PhysicalTransferType4Code string

type PolypropyleneCommodityPlastic1 struct {
	BasePdct AssetClassProductType9Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType18Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubPdct,omitempty"`
}

// May be one of PNDG, NOAP
type PriceStatus1Code string

// May be one of DAYS, MNTH, WEEK, YEAR
type RateBasis1Code string

type RecordTechnicalData4 struct {
	IncnsstncyInd      bool          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IncnsstncyInd,omitempty"`
	LastUpd            ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 LastUpd,omitempty"`
	SubmissnDtTm       ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubmissnDtTm,omitempty"`
	RlvntCmptntAuthrty CountryCode   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RlvntCmptntAuthrty,omitempty"`
	PblctnPrd          Period4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 PblctnPrd,omitempty"`
	NvrPblshd          bool          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NvrPblshd,omitempty"`
	RlvntTradgVn       MICIdentifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RlvntTradgVn,omitempty"`
}

type SecuritiesMarketReportHeader1 struct {
	RptgNtty     TradingVenueIdentification1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RptgNtty"`
	RptgPrd      Period4Choice                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 RptgPrd"`
	SubmissnDtTm ISODateTime                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 SubmissnDtTm,omitempty"`
}

type SecuritiesReferenceDataReport6 struct {
	TechRcrdId          Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TechRcrdId,omitempty"`
	FinInstrmGnlAttrbts SecurityInstrumentDescription9 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FinInstrmGnlAttrbts"`
	Issr                LEIIdentifier                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Issr"`
	TradgVnRltdAttrbts  []TradingVenueAttributes1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TradgVnRltdAttrbts"`
	DebtInstrmAttrbts   DebtInstrument2                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 DebtInstrmAttrbts,omitempty"`
	DerivInstrmAttrbts  DerivativeInstrument5          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 DerivInstrmAttrbts,omitempty"`
	TechAttrbts         RecordTechnicalData4           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TechAttrbts,omitempty"`
}

type SecuritiesReferenceDeltaStatusReport3Choice struct {
	ModfdRcrd   SecuritiesReferenceDataReport6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ModfdRcrd,omitempty"`
	NewRcrd     SecuritiesReferenceDataReport6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NewRcrd,omitempty"`
	TermntdRcrd SecuritiesReferenceDataReport6 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TermntdRcrd,omitempty"`
}

type SecuritiesTransactionPrice1 struct {
	Pdg PriceStatus1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Pdg"`
	Ccy ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Ccy,omitempty"`
}

type SecuritiesTransactionPrice2Choice struct {
	MntryVal AmountAndDirection61 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 MntryVal,omitempty"`
	Pctg     float64              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Pctg,omitempty"`
	Yld      float64              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Yld,omitempty"`
	BsisPts  float64              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 BsisPts,omitempty"`
}

type SecuritiesTransactionPrice4Choice struct {
	Pric   SecuritiesTransactionPrice2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Pric,omitempty"`
	NoPric SecuritiesTransactionPrice1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NoPric,omitempty"`
}

type SecurityInstrumentDescription9 struct {
	Id             ISINOct2015Identifier        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Id"`
	FullNm         Max350Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FullNm"`
	ShrtNm         Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ShrtNm,omitempty"`
	ClssfctnTp     CFIOct2015Identifier         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ClssfctnTp"`
	NtnlCcy        ActiveOrHistoricCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NtnlCcy"`
	CmmdtyDerivInd bool                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 CmmdtyDerivInd"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

// May be one of APPA, CTPS
type TradingVenue2Code string

type TradingVenueAttributes1 struct {
	Id                   MICIdentifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Id"`
	IssrReq              bool          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 IssrReq"`
	AdmssnApprvlDtByIssr ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 AdmssnApprvlDtByIssr,omitempty"`
	ReqForAdmssnDt       ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 ReqForAdmssnDt,omitempty"`
	FrstTradDt           ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 FrstTradDt,omitempty"`
	TermntnDt            ISODateTime   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 TermntnDt,omitempty"`
}

type TradingVenueIdentification1Choice struct {
	MktIdCd          MICIdentifier               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 MktIdCd,omitempty"`
	NtlCmptntAuthrty CountryCode                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 NtlCmptntAuthrty,omitempty"`
	Othr             TradingVenueIdentification2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Othr,omitempty"`
}

type TradingVenueIdentification2 struct {
	Id Max50Text         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Id"`
	Tp TradingVenue2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.036.001.02 Tp"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
