// Code generated by download. DO NOT EDIT.

package iso20022_auth_084_001_02

type AgreementType2Choice struct {
	Tp    ExternalAgreementType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Tp,omitempty"`
	Prtry Max50Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Prtry,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type DetailedReportStatistics5 struct {
	TtlNbOfRpts         Max15NumericText                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfRpts"`
	TtlNbOfRptsAccptd   Max15NumericText                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfRptsAccptd"`
	TtlNbOfRptsRjctd    Max15NumericText                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfRptsRjctd"`
	NbOfRptsRjctdPerErr []NumberOfTransactionsPerValidationRule5 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 NbOfRptsRjctdPerErr,omitempty"`
}

type DetailedTransactionStatistics13 struct {
	TtlNbOfTxs       Max15NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfTxs"`
	TtlNbOfTxsAccptd Max15NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfTxsAccptd"`
	TtlNbOfTxsRjctd  Max15NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TtlNbOfTxsRjctd"`
	TxsRjctnsRsn     []RejectionReason53 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TxsRjctnsRsn,omitempty"`
}

type DetailedTransactionStatistics2Choice struct {
	DataSetActn ReportPeriodActivity1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DataSetActn,omitempty"`
	DtldSttstcs DetailedTransactionStatistics13 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DtldSttstcs,omitempty"`
}

type Document struct {
	SctiesFincgRptgTxStsAdvc SecuritiesFinancingReportingTransactionStatusAdviceV02 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 SctiesFincgRptgTxStsAdvc"`
}

// May be no more than 4 items long
type ExternalAgreementType1Code string

// May be no more than 4 items long
type ExternalValidationRuleIdentification1Code string

type GenericIdentification175 struct {
	Id      Max72Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Id"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 SchmeNm,omitempty"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Issr,omitempty"`
}

type GenericValidationRuleIdentification1 struct {
	Id      Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Id"`
	Desc    Max350Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Desc,omitempty"`
	SchmeNm ValidationRuleSchemeName1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 SchmeNm,omitempty"`
	Issr    Max35Text                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Issr,omitempty"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

type MasterAgreement7 struct {
	Tp                AgreementType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Tp"`
	Vrsn              Max50Text            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Vrsn,omitempty"`
	OthrMstrAgrmtDtls Max350Text           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 OthrMstrAgrmtDtls,omitempty"`
}

// May be no more than 105 items long
type Max105Text string

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 500 items long
type Max500Text string

// May be no more than 50 items long
type Max50Text string

// May be no more than 52 items long
type Max52Text string

// May be no more than 72 items long
type Max72Text string

type NaturalPersonIdentification2 struct {
	Id   GenericIdentification175 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Id"`
	Nm   Max105Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Nm,omitempty"`
	Dmcl Max500Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Dmcl,omitempty"`
}

type NumberOfTransactionsPerValidationRule5 struct {
	DtldNb Max15NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DtldNb"`
	RptSts []RejectionReason45 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptSts"`
}

type OrganisationIdentification15Choice struct {
	LEI    LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 LEI,omitempty"`
	Othr   OrganisationIdentification38 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Othr,omitempty"`
	AnyBIC AnyBICDec2014Identifier      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 AnyBIC,omitempty"`
}

type OrganisationIdentification38 struct {
	Id   GenericIdentification175 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Id"`
	Nm   Max105Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Nm,omitempty"`
	Dmcl Max500Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Dmcl,omitempty"`
}

type PartyIdentification236Choice struct {
	Lgl  OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Lgl,omitempty"`
	Ntrl NaturalPersonIdentification2       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Ntrl,omitempty"`
}

type RejectionReason45 struct {
	MsgRptId      Max140Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 MsgRptId"`
	Sts           ReportingMessageStatus1Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Sts"`
	DtldVldtnRule GenericValidationRuleIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DtldVldtnRule,omitempty"`
}

type RejectionReason53 struct {
	TxId          TransactionIdentification3Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TxId"`
	Sts           ReportingMessageStatus1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Sts"`
	DtldVldtnRule []GenericValidationRuleIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DtldVldtnRule,omitempty"`
}

// May be one of NOTX
type ReportPeriodActivity1Code string

// May be one of ACPT, ACTC, PART, RCVD, RJCT, RMDR, WARN, INCF, CRPT
type ReportingMessageStatus1Code string

type SecuritiesFinancingReportingTransactionStatusAdviceV02 struct {
	TxRptStsAndRsn []TradeData35Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TxRptStsAndRsn"`
	SplmtryData    []SupplementaryData1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 SplmtryData,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TradeData29 struct {
	RptSttstcs  []DetailedReportStatistics5            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptSttstcs"`
	TxSttstcs   []DetailedTransactionStatistics2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TxSttstcs"`
	SplmtryData []SupplementaryData1                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 SplmtryData,omitempty"`
}

type TradeData35Choice struct {
	DataSetActn ReportPeriodActivity1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 DataSetActn,omitempty"`
	Rpt         []TradeData29             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Rpt,omitempty"`
}

type TradeTransactionIdentification16 struct {
	TechRcrdId        Max140Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TechRcrdId,omitempty"`
	RptgCtrPty        OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptgCtrPty"`
	OthrCtrPty        PartyIdentification236Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 OthrCtrPty"`
	NttyRspnsblForRpt OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 NttyRspnsblForRpt,omitempty"`
	CollPrtflId       Max52Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 CollPrtflId,omitempty"`
}

type TradeTransactionIdentification17 struct {
	TechRcrdId        Max140Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TechRcrdId,omitempty"`
	RptgCtrPty        OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptgCtrPty"`
	RptSubmitgNtty    OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptSubmitgNtty"`
	NttyRspnsblForRpt OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 NttyRspnsblForRpt,omitempty"`
}

type TradeTransactionIdentification20 struct {
	TechRcrdId        Max140Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TechRcrdId,omitempty"`
	RptgCtrPty        OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 RptgCtrPty"`
	OthrCtrPty        PartyIdentification236Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 OthrCtrPty"`
	NttyRspnsblForRpt OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 NttyRspnsblForRpt,omitempty"`
	UnqTradIdr        Max52Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 UnqTradIdr,omitempty"`
	MstrAgrmt         MasterAgreement7                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 MstrAgrmt,omitempty"`
	AgtLndr           OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 AgtLndr,omitempty"`
	TrptyAgt          OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 TrptyAgt,omitempty"`
}

type TransactionIdentification3Choice struct {
	Tx        TradeTransactionIdentification20 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Tx,omitempty"`
	MrgnRptg  TradeTransactionIdentification16 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 MrgnRptg,omitempty"`
	CollReuse TradeTransactionIdentification17 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 CollReuse,omitempty"`
}

type ValidationRuleSchemeName1Choice struct {
	Cd    ExternalValidationRuleIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Cd,omitempty"`
	Prtry Max35Text                                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.084.001.02 Prtry,omitempty"`
}
