// Code generated by download. DO NOT EDIT.

package iso20022_auth_079_001_02

import (
	"bytes"
	"encoding/xml"
	"time"
)

type ActiveOrHistoricCurrencyAnd20DecimalAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

type AgreementType2Choice struct {
	Tp    ExternalAgreementType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp,omitempty"`
	Prtry Max50Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Prtry,omitempty"`
}

type AgriculturalCommodityDairy1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType20Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommodityForestry1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType21Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommodityGrain2 struct {
	BasePdct     AssetClassProductType1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType5Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType30Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type AgriculturalCommodityLiveStock1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType22Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommodityOilSeed1 struct {
	BasePdct     AssetClassProductType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type AgriculturalCommodityOliveOil2 struct {
	BasePdct     AssetClassProductType1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType3Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType29Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type AgriculturalCommodityOther1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommodityPotato1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType45Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommoditySeafood1 struct {
	BasePdct AssetClassProductType1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType23Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type AgriculturalCommoditySoft1 struct {
	BasePdct     AssetClassProductType1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType2Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type AmountAndDirection107 struct {
	Amt ActiveOrHistoricCurrencyAnd20DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Amt"`
	Sgn bool                                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Sgn,omitempty"`
}

type AmountAndDirection53 struct {
	Amt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Amt"`
	Sgn bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Sgn,omitempty"`
}

type AmountHaircutMargin1 struct {
	Amt         AmountAndDirection53 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Amt"`
	HrcutOrMrgn float64              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 HrcutOrMrgn,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

type AssetClassCommodity5Choice struct {
	Agrcltrl          AssetClassCommodityAgricultural5Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Agrcltrl,omitempty"`
	Nrgy              AssetClassCommodityEnergy2Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Nrgy,omitempty"`
	Envttl            AssetClassCommodityEnvironmental2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Envttl,omitempty"`
	Frtlzr            AssetClassCommodityFertilizer3Choice           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Frtlzr,omitempty"`
	Frght             AssetClassCommodityFreight3Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Frght,omitempty"`
	IndstrlPdct       AssetClassCommodityIndustrialProduct1Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 IndstrlPdct,omitempty"`
	Metl              AssetClassCommodityMetal1Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Metl,omitempty"`
	OthrC10           AssetClassCommodityOtherC102Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OthrC10,omitempty"`
	Ppr               AssetClassCommodityPaper3Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ppr,omitempty"`
	Plprpln           AssetClassCommodityPolypropylene3Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Plprpln,omitempty"`
	Infltn            AssetClassCommodityInflation1                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Infltn,omitempty"`
	MultiCmmdtyExtc   AssetClassCommodityMultiCommodityExotic1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MultiCmmdtyExtc,omitempty"`
	OffclEcnmcSttstcs AssetClassCommodityOfficialEconomicStatistics1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OffclEcnmcSttstcs,omitempty"`
	Othr              AssetClassCommodityOther1                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityAgricultural5Choice struct {
	GrnOilSeed AgriculturalCommodityOilSeed1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 GrnOilSeed,omitempty"`
	Soft       AgriculturalCommoditySoft1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Soft,omitempty"`
	Ptt        AgriculturalCommodityPotato1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ptt,omitempty"`
	OlvOil     AgriculturalCommodityOliveOil2  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OlvOil,omitempty"`
	Dairy      AgriculturalCommodityDairy1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dairy,omitempty"`
	Frstry     AgriculturalCommodityForestry1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Frstry,omitempty"`
	Sfd        AgriculturalCommoditySeafood1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Sfd,omitempty"`
	LiveStock  AgriculturalCommodityLiveStock1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LiveStock,omitempty"`
	Grn        AgriculturalCommodityGrain2     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Grn,omitempty"`
	Othr       AgriculturalCommodityOther1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityEnergy2Choice struct {
	Elctrcty  EnergyCommodityElectricity1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Elctrcty,omitempty"`
	NtrlGas   EnergyCommodityNaturalGas2      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NtrlGas,omitempty"`
	Oil       EnergyCommodityOil2             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Oil,omitempty"`
	Coal      EnergyCommodityCoal1            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Coal,omitempty"`
	IntrNrgy  EnergyCommodityInterEnergy1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 IntrNrgy,omitempty"`
	RnwblNrgy EnergyCommodityRenewableEnergy1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RnwblNrgy,omitempty"`
	LghtEnd   EnergyCommodityLightEnd1        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LghtEnd,omitempty"`
	Dstllts   EnergyCommodityDistillates1     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dstllts,omitempty"`
	Othr      EnergyCommodityOther1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityEnvironmental2Choice struct {
	Emssns   EnvironmentalCommodityEmission2      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Emssns,omitempty"`
	Wthr     EnvironmentalCommodityWeather1       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Wthr,omitempty"`
	CrbnRltd EnvironmentalCommodityCarbonRelated1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CrbnRltd,omitempty"`
	Othr     EnvironmentCommodityOther1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityFertilizer3Choice struct {
	Ammn             FertilizerCommodityAmmonia1                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ammn,omitempty"`
	DmmnmPhspht      FertilizerCommodityDiammoniumPhosphate1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DmmnmPhspht,omitempty"`
	Ptsh             FertilizerCommodityPotash1                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ptsh,omitempty"`
	Slphr            FertilizerCommoditySulphur1                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Slphr,omitempty"`
	Urea             FertilizerCommodityUrea1                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Urea,omitempty"`
	UreaAndAmmnmNtrt FertilizerCommodityUreaAndAmmoniumNitrate1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UreaAndAmmnmNtrt,omitempty"`
	Othr             FertilizerCommodityOther1                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityFreight3Choice struct {
	Dry       FreightCommodityDry2           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dry,omitempty"`
	Wet       FreightCommodityWet2           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Wet,omitempty"`
	CntnrShip FreightCommodityContainerShip1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CntnrShip,omitempty"`
	Othr      FreightCommodityOther1         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityIndustrialProduct1Choice struct {
	Cnstrctn IndustrialProductCommodityConstruction1  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Cnstrctn,omitempty"`
	Manfctg  IndustrialProductCommodityManufacturing1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Manfctg,omitempty"`
}

type AssetClassCommodityInflation1 struct {
	BasePdct AssetClassProductType12Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
}

type AssetClassCommodityMetal1Choice struct {
	NonPrcs MetalCommodityNonPrecious1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NonPrcs,omitempty"`
	Prcs    MetalCommodityPrecious1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Prcs,omitempty"`
}

type AssetClassCommodityMultiCommodityExotic1 struct {
	BasePdct AssetClassProductType13Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
}

type AssetClassCommodityOfficialEconomicStatistics1 struct {
	BasePdct AssetClassProductType14Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
}

type AssetClassCommodityOther1 struct {
	BasePdct AssetClassProductType15Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
}

type AssetClassCommodityOtherC102Choice struct {
	Dlvrbl    OtherC10CommodityDeliverable2    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dlvrbl,omitempty"`
	NonDlvrbl OtherC10CommodityNonDeliverable2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NonDlvrbl,omitempty"`
}

type AssetClassCommodityPaper3Choice struct {
	CntnrBrd PaperCommodityContainerBoard1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CntnrBrd,omitempty"`
	Nwsprnt  PaperCommodityNewsprint1      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Nwsprnt,omitempty"`
	Pulp     PaperCommodityPulp1           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Pulp,omitempty"`
	RcvrdPpr PaperCommodityRecoveredPaper1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RcvrdPpr,omitempty"`
	Othr     PaperCommodityRecoveredPaper2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type AssetClassCommodityPolypropylene3Choice struct {
	Plstc PolypropyleneCommodityPlastic1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Plstc,omitempty"`
	Othr  PolypropyleneCommodityOther1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

// May be one of ALUM, ALUA, CBLT, COPR, IRON, MOLY, NASC, NICK, STEL, TINN, ZINC, OTHR, LEAD
type AssetClassDetailedSubProductType10Code string

// May be one of GOLD, OTHR, PLDM, PTNM, SLVR
type AssetClassDetailedSubProductType11Code string

// May be one of FWHT, SOYB, RPSD, OTHR, CORN, RICE
type AssetClassDetailedSubProductType1Code string

// May be one of LAMP, OTHR
type AssetClassDetailedSubProductType29Code string

// May be one of ROBU, CCOA, BRWN, WHSG, OTHR
type AssetClassDetailedSubProductType2Code string

// May be one of MWHT, OTHR
type AssetClassDetailedSubProductType30Code string

// May be one of GASP, LNGG, NCGG, TTFG, NBPG, OTHR
type AssetClassDetailedSubProductType31Code string

// May be one of BAKK, BDSL, BRNT, BRNX, CNDA, COND, DSEL, DUBA, ESPO, ETHA, FUEL, FOIL, GOIL, GSLN, HEAT, JTFL, KERO, LLSO, MARS, NAPH, NGLO, TAPI, WTIO, URAL, OTHR
type AssetClassDetailedSubProductType32Code string

// May be one of DBCR, OTHR
type AssetClassDetailedSubProductType33Code string

// May be one of TNKR, OTHR
type AssetClassDetailedSubProductType34Code string

// May be one of BSLD, FITR, PKLD, OFFP, OTHR
type AssetClassDetailedSubProductType5Code string

// May be one of CERE, ERUE, EUAE, EUAA, OTHR
type AssetClassDetailedSubProductType8Code string

// May be one of OTHC
type AssetClassProductType11Code string

// May be one of INFL
type AssetClassProductType12Code string

// May be one of MCEX
type AssetClassProductType13Code string

// May be one of OEST
type AssetClassProductType14Code string

// May be one of OTHR
type AssetClassProductType15Code string

// May be one of AGRI
type AssetClassProductType1Code string

// May be one of NRGY
type AssetClassProductType2Code string

// May be one of ENVR
type AssetClassProductType3Code string

// May be one of FRGT
type AssetClassProductType4Code string

// May be one of FRTL
type AssetClassProductType5Code string

// May be one of INDP
type AssetClassProductType6Code string

// May be one of METL
type AssetClassProductType7Code string

// May be one of PAPR
type AssetClassProductType8Code string

// May be one of POLY
type AssetClassProductType9Code string

// May be one of EMIS
type AssetClassSubProductType10Code string

// May be one of NPRM
type AssetClassSubProductType15Code string

// May be one of PRME
type AssetClassSubProductType16Code string

// May be one of PLST
type AssetClassSubProductType18Code string

// May be one of GROS
type AssetClassSubProductType1Code string

// May be one of DIRY
type AssetClassSubProductType20Code string

// May be one of FRST
type AssetClassSubProductType21Code string

// May be one of LSTK
type AssetClassSubProductType22Code string

// May be one of SEAF
type AssetClassSubProductType23Code string

// May be one of COAL
type AssetClassSubProductType24Code string

// May be one of DIST
type AssetClassSubProductType25Code string

// May be one of INRG
type AssetClassSubProductType26Code string

// May be one of LGHT
type AssetClassSubProductType27Code string

// May be one of RNNG
type AssetClassSubProductType28Code string

// May be one of CRBR
type AssetClassSubProductType29Code string

// May be one of SOFT
type AssetClassSubProductType2Code string

// May be one of WTHR
type AssetClassSubProductType30Code string

// May be one of DRYF
type AssetClassSubProductType31Code string

// May be one of WETF
type AssetClassSubProductType32Code string

// May be one of CSTR
type AssetClassSubProductType33Code string

// May be one of MFTG
type AssetClassSubProductType34Code string

// May be one of CBRD
type AssetClassSubProductType35Code string

// May be one of NSPT
type AssetClassSubProductType36Code string

// May be one of PULP
type AssetClassSubProductType37Code string

// May be one of RCVP
type AssetClassSubProductType38Code string

// May be one of AMMO
type AssetClassSubProductType39Code string

// May be one of OOLI
type AssetClassSubProductType3Code string

// May be one of DAPH
type AssetClassSubProductType40Code string

// May be one of PTSH
type AssetClassSubProductType41Code string

// May be one of SLPH
type AssetClassSubProductType42Code string

// May be one of UREA
type AssetClassSubProductType43Code string

// May be one of UAAN
type AssetClassSubProductType44Code string

// May be one of POTA
type AssetClassSubProductType45Code string

// May be one of CSHP
type AssetClassSubProductType46Code string

// May be one of DLVR
type AssetClassSubProductType47Code string

// May be one of NDLV
type AssetClassSubProductType48Code string

// May be one of OTHR
type AssetClassSubProductType49Code string

// May be one of GRIN
type AssetClassSubProductType5Code string

// May be one of ELEC
type AssetClassSubProductType6Code string

// May be one of NGAS
type AssetClassSubProductType7Code string

// May be one of OILP
type AssetClassSubProductType8Code string

type BenchmarkCurveName10Choice struct {
	Indx BenchmarkCurveName3Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Indx,omitempty"`
	Nm   Max350Text              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Nm,omitempty"`
}

// May be one of ESTR, BBSW, BUBO, CDOR, CIBO, EONA, EONS, EURI, EUUS, EUCH, FUSW, GCFR, ISDA, JIBA, LIBI, LIBO, MOSP, MAAA, NIBO, PFAN, PRBO, STBO, SWAP, TLBO, TIBO, TREA, WIBO, SOFR, SONA
type BenchmarkCurveName3Code string

type Branch5Choice struct {
	Id   OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	Ctry CountryCode                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ctry,omitempty"`
}

type Branch6Choice struct {
	Id   PartyIdentification236Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	Ctry CountryCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ctry,omitempty"`
}

// Must match the pattern [A-Z]{6,6}
type CFIOct2015Identifier string

type Cleared16Choice struct {
	Clrd    ClearingPartyAndTime14 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Clrd,omitempty"`
	NonClrd NoReasonCode           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NonClrd,omitempty"`
}

type ClearingPartyAndTime14 struct {
	CCP        OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CCP,omitempty"`
	ClrDtTm    ISODateTime                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClrDtTm,omitempty"`
	RptTrckgNb Max52Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RptTrckgNb,omitempty"`
	PrtflCd    Max52Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PrtflCd,omitempty"`
}

type Collateral52 struct {
	CollValDt         ISODate                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollValDt,omitempty"`
	AsstTp            CollateralType21               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AsstTp,omitempty"`
	NetXpsrCollstnInd bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NetXpsrCollstnInd,omitempty"`
	BsktIdr           SecurityIdentification26Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BsktIdr,omitempty"`
}

// May be one of SICA, SIUR, TTCA
type CollateralDeliveryMethod1Code string

type CollateralFlag13Choice struct {
	Collsd   CollaterisedData12 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Collsd,omitempty"`
	Uncollsd NoReasonCode       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Uncollsd,omitempty"`
}

// May be one of INVG, NIVG, NOTR, NOAP
type CollateralQualityType1Code string

// May be one of GIVE, TAKE
type CollateralRole1Code string

type CollateralType21 struct {
	Scty   []Security52           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Scty,omitempty"`
	Csh    []AmountHaircutMargin1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Csh,omitempty"`
	Cmmdty []Commodity43          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Cmmdty,omitempty"`
}

type CollaterisedData12 struct {
	CollValDt         ISODate                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollValDt,omitempty"`
	AsstTp            CollateralType21               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AsstTp,omitempty"`
	NetXpsrCollstnInd bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NetXpsrCollstnInd,omitempty"`
	BsktIdr           SecurityIdentification26Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BsktIdr,omitempty"`
}

type Commodity43 struct {
	Clssfctn AssetClassCommodity5Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Clssfctn,omitempty"`
	Qty      Quantity17                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Qty,omitempty"`
	UnitPric SecuritiesTransactionPrice19Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitPric,omitempty"`
	MktVal   AmountAndDirection53               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MktVal,omitempty"`
}

type ContractModification3 struct {
	ActnTp TransactionOperationType6Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ActnTp"`
	Lvl    ModificationLevel1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Lvl,omitempty"`
}

type ContractTerm7Choice struct {
	Opn FixedOpenTermContract2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Opn,omitempty"`
	Fxd FixedOpenTermContract2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Fxd,omitempty"`
}

type CounterpartyData88 struct {
	RptgDtTm       ISODateTime                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RptgDtTm"`
	RptSubmitgNtty OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RptSubmitgNtty"`
	CtrPty         []CounterpartyData89               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CtrPty"`
}

type CounterpartyData89 struct {
	RptgCtrPty        CounterpartyIdentification11       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RptgCtrPty"`
	OthrCtrPty        CounterpartyIdentification12       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OthrCtrPty"`
	NttyRspnsblForRpt OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NttyRspnsblForRpt,omitempty"`
	OthrPtyData       TransactionCounterpartyData11      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OthrPtyData,omitempty"`
}

type CounterpartyIdentification11 struct {
	Id    OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id"`
	Ntr   CounterpartyTradeNature7Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ntr,omitempty"`
	Brnch Branch5Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Brnch,omitempty"`
	Sd    CollateralRole1Code                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Sd,omitempty"`
}

type CounterpartyIdentification12 struct {
	Id     PartyIdentification236Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id"`
	Brnch  Branch6Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Brnch,omitempty"`
	CtryCd CountryCode                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CtryCd,omitempty"`
}

type CounterpartyTradeNature7Choice struct {
	FI  FinancialPartyClassification1   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 FI,omitempty"`
	NFI []FinancialPartyClassification2 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NFI,omitempty"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

type Document struct {
	SctiesFincgRptgTxStatRpt SecuritiesFinancingReportingTransactionStateReportV02 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SctiesFincgRptgTxStatRpt"`
}

type EnergyCommodityCoal1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType24Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnergyCommodityDistillates1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType25Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnergyCommodityElectricity1 struct {
	BasePdct     AssetClassProductType2Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType6Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType5Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type EnergyCommodityInterEnergy1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType26Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnergyCommodityLightEnd1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType27Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnergyCommodityNaturalGas2 struct {
	BasePdct     AssetClassProductType2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType7Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType31Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type EnergyCommodityOil2 struct {
	BasePdct     AssetClassProductType2Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType8Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType32Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type EnergyCommodityOther1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnergyCommodityRenewableEnergy1 struct {
	BasePdct AssetClassProductType2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType28Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnvironmentCommodityOther1 struct {
	BasePdct AssetClassProductType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnvironmentalCommodityCarbonRelated1 struct {
	BasePdct AssetClassProductType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType29Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type EnvironmentalCommodityEmission2 struct {
	BasePdct     AssetClassProductType3Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType10Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType8Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type EnvironmentalCommodityWeather1 struct {
	BasePdct AssetClassProductType3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType30Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

// May be no more than 4 items long
type ExternalAgreementType1Code string

// May be no more than 4 items long
type ExternalSecuritiesLendingType1Code string

type FertilizerCommodityAmmonia1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType39Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommodityDiammoniumPhosphate1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType40Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommodityOther1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommodityPotash1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType41Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommoditySulphur1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType42Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommodityUrea1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType43Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FertilizerCommodityUreaAndAmmoniumNitrate1 struct {
	BasePdct AssetClassProductType5Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType44Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FinancialPartyClassification1 struct {
	Clssfctn           []FinancialPartySectorType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Clssfctn"`
	InvstmtFndClssfctn FundType2Code                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 InvstmtFndClssfctn,omitempty"`
}

type FinancialPartyClassification2 struct {
	Clssfctn           []NACEDomainIdentifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Clssfctn"`
	InvstmtFndClssfctn FundType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 InvstmtFndClssfctn,omitempty"`
}

// May be one of AIFD, CSDS, CCPS, CDTI, INUN, ORPI, INVF, REIN, UCIT
type FinancialPartySectorType2Code string

type FixedOpenTermContract2 struct {
	MtrtyDt     ISODate                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MtrtyDt,omitempty"`
	TermntnOptn RepoTerminationOption2Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TermntnOptn,omitempty"`
}

type FixedRate11 struct {
	Rate       float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Rate,omitempty"`
	DayCntBsis InterestComputationMethodFormat6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DayCntBsis,omitempty"`
}

type FloatingInterestRate22 struct {
	RefRate      BenchmarkCurveName10Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RefRate,omitempty"`
	Term         InterestRateContractTerm2              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Term,omitempty"`
	PmtFrqcy     InterestRateContractTerm2              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PmtFrqcy,omitempty"`
	RstFrqcy     InterestRateContractTerm2              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RstFrqcy,omitempty"`
	Sprd         SecuritiesTransactionPrice18Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Sprd,omitempty"`
	RateAdjstmnt []RateAdjustment1                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RateAdjstmnt,omitempty"`
	DayCntBsis   InterestComputationMethodFormat6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DayCntBsis,omitempty"`
}

type FreightCommodityContainerShip1 struct {
	BasePdct AssetClassProductType4Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType46Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FreightCommodityDry2 struct {
	BasePdct     AssetClassProductType4Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType31Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType33Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type FreightCommodityOther1 struct {
	BasePdct AssetClassProductType4Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type FreightCommodityWet2 struct {
	BasePdct     AssetClassProductType4Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType32Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType34Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

// May be one of ETFT, MMFT, OTHR, REIT
type FundType2Code string

type GenericIdentification175 struct {
	Id      Max72Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id"`
	SchmeNm Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SchmeNm,omitempty"`
	Issr    Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Issr,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IndustrialProductCommodityConstruction1 struct {
	BasePdct AssetClassProductType6Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType33Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type IndustrialProductCommodityManufacturing1 struct {
	BasePdct AssetClassProductType6Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType34Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

// May be one of A001, A002, A003, A004, A005, A006, A007, A008, A009, A010, A011, A012, A013, A014
type InterestComputationMethod1Code string

type InterestComputationMethodFormat6Choice struct {
	Cd    InterestComputationMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Cd,omitempty"`
	Prtry Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Prtry,omitempty"`
}

type InterestRate27Choice struct {
	Fxd  FixedRate11            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Fxd,omitempty"`
	Fltg FloatingInterestRate22 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Fltg,omitempty"`
}

type InterestRate6 struct {
	Amt        AmountAndDirection53 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Amt"`
	IntrstRate InterestRate27Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 IntrstRate"`
}

type InterestRateContractTerm2 struct {
	Unit RateBasis1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Unit"`
	Val  float64        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Val"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

type LoanData139 struct {
	UnqTradIdr      Max52Text                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnqTradIdr,omitempty"`
	EvtDt           ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 EvtDt,omitempty"`
	ExctnDtTm       ISODateTime                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExctnDtTm,omitempty"`
	ClrSts          Cleared16Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClrSts,omitempty"`
	TradgVn         MICIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TradgVn,omitempty"`
	MstrAgrmt       MasterAgreement7              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MstrAgrmt,omitempty"`
	ValDt           ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ValDt,omitempty"`
	MinNtcePrd      float64                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MinNtcePrd,omitempty"`
	EarlstCallBckDt ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 EarlstCallBckDt,omitempty"`
	GnlColl         SpecialCollateral1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 GnlColl,omitempty"`
	DlvryByVal      bool                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DlvryByVal,omitempty"`
	CollDlvryMtd    CollateralDeliveryMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollDlvryMtd,omitempty"`
	Term            []ContractTerm7Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Term,omitempty"`
	IntrstRate      InterestRate27Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 IntrstRate,omitempty"`
	PrncplAmt       PrincipalAmount3              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PrncplAmt,omitempty"`
	TermntnDt       ISODate                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TermntnDt,omitempty"`
}

type LoanData140 struct {
	UnqTradIdr Max52Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnqTradIdr,omitempty"`
	EvtDt      ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 EvtDt"`
	ExctnDtTm  ISODateTime                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExctnDtTm,omitempty"`
	ClrSts     Cleared16Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClrSts,omitempty"`
	TradgVn    MICIdentifier                      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TradgVn,omitempty"`
	MstrAgrmt  MasterAgreement7                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MstrAgrmt,omitempty"`
	ValDt      ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ValDt,omitempty"`
	MtrtyDt    ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MtrtyDt,omitempty"`
	GnlColl    SpecialCollateral1Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 GnlColl,omitempty"`
	PrncplAmt  PrincipalAmount3                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PrncplAmt,omitempty"`
	UnitPric   SecuritiesTransactionPrice19Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitPric,omitempty"`
	TermntnDt  ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TermntnDt,omitempty"`
}

type LoanData141 struct {
	UnqTradIdr   Max52Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnqTradIdr,omitempty"`
	EvtDt        ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 EvtDt"`
	ExctnDtTm    ISODateTime                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExctnDtTm,omitempty"`
	ClrSts       Cleared16Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClrSts,omitempty"`
	TradgVn      MICIdentifier                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TradgVn,omitempty"`
	MstrAgrmt    MasterAgreement7                  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MstrAgrmt,omitempty"`
	ValDt        ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ValDt,omitempty"`
	GnlColl      SpecialCollateral1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 GnlColl,omitempty"`
	DlvryByVal   bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DlvryByVal,omitempty"`
	CollDlvryMtd CollateralDeliveryMethod1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollDlvryMtd,omitempty"`
	Term         []ContractTerm7Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Term,omitempty"`
	AsstTp       SecurityCommodity9                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AsstTp,omitempty"`
	LnVal        ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LnVal,omitempty"`
	RbtRate      InterestRate27Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RbtRate,omitempty"`
	LndgFee      float64                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LndgFee,omitempty"`
	TermntnDt    ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TermntnDt,omitempty"`
}

type LoanData142 struct {
	UnqTradIdr       Max52Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnqTradIdr,omitempty"`
	EvtDt            ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 EvtDt"`
	ExctnDtTm        ISODateTime                       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExctnDtTm,omitempty"`
	TradgVn          MICIdentifier                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TradgVn,omitempty"`
	CollDlvryMtd     CollateralDeliveryMethod1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollDlvryMtd,omitempty"`
	OutsdngMrgnLnAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OutsdngMrgnLnAmt,omitempty"`
	ShrtMktValAmt    ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ShrtMktValAmt,omitempty"`
	MrgnLnAttr       []InterestRate6                   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MrgnLnAttr,omitempty"`
	TermntnDt        ISODate                           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TermntnDt,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}
type MICIdentifier string

type MasterAgreement7 struct {
	Tp                AgreementType2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp"`
	Vrsn              Max50Text            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Vrsn,omitempty"`
	OthrMstrAgrmtDtls Max350Text           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 OthrMstrAgrmtDtls,omitempty"`
}

// May be no more than 105 items long
type Max105Text string

// May be no more than 140 items long
type Max140Text string

// May be no more than 350 items long
type Max350Text string

// May be no more than 35 items long
type Max35Text string

// May be no more than 500 items long
type Max500Text string

// May be no more than 50 items long
type Max50Text string

// May be no more than 52 items long
type Max52Text string

// May be no more than 72 items long
type Max72Text string

type MetalCommodityNonPrecious1 struct {
	BasePdct     AssetClassProductType7Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType15Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType10Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

type MetalCommodityPrecious1 struct {
	BasePdct     AssetClassProductType7Code             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct      AssetClassSubProductType16Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
	AddtlSubPdct AssetClassDetailedSubProductType11Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AddtlSubPdct"`
}

// May be one of PSTN, TCTN
type ModificationLevel1Code string

// Must match the pattern [A-U]{1,1}
type NACEDomainIdentifier string

type NaturalPersonIdentification2 struct {
	Id   GenericIdentification175 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id"`
	Nm   Max105Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Nm,omitempty"`
	Dmcl Max500Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dmcl,omitempty"`
}

// May be one of NORE
type NoReasonCode string

// May be one of NTAV
type NotAvailable1Code string

type OrganisationIdentification15Choice struct {
	LEI    LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LEI,omitempty"`
	Othr   OrganisationIdentification38 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
	AnyBIC AnyBICDec2014Identifier      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AnyBIC,omitempty"`
}

type OrganisationIdentification38 struct {
	Id   GenericIdentification175 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id"`
	Nm   Max105Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Nm,omitempty"`
	Dmcl Max500Text               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dmcl,omitempty"`
}

type OtherC10CommodityDeliverable2 struct {
	BasePdct AssetClassProductType11Code    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType47Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type OtherC10CommodityNonDeliverable2 struct {
	BasePdct AssetClassProductType11Code    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType48Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PaperCommodityContainerBoard1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType35Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PaperCommodityNewsprint1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType36Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PaperCommodityPulp1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType37Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PaperCommodityRecoveredPaper1 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType38Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PaperCommodityRecoveredPaper2 struct {
	BasePdct AssetClassProductType8Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

type PartyIdentification236Choice struct {
	Lgl  OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Lgl,omitempty"`
	Ntrl NaturalPersonIdentification2       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Ntrl,omitempty"`
}

type PolypropyleneCommodityOther1 struct {
	BasePdct AssetClassProductType9Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType49Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct"`
}

type PolypropyleneCommodityPlastic1 struct {
	BasePdct AssetClassProductType9Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BasePdct"`
	SubPdct  AssetClassSubProductType18Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SubPdct,omitempty"`
}

// May be one of PNDG, NOAP
type PriceStatus1Code string

type PrincipalAmount3 struct {
	ValDtAmt   ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ValDtAmt,omitempty"`
	MtrtyDtAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MtrtyDtAmt,omitempty"`
}

type Quantity17 struct {
	Val         float64             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Val"`
	UnitOfMeasr UnitOfMeasure11Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitOfMeasr"`
}

type QuantityNominalValue2Choice struct {
	Qty     float64              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Qty,omitempty"`
	NmnlVal AmountAndDirection53 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NmnlVal,omitempty"`
}

type RateAdjustment1 struct {
	Rate       float64 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Rate"`
	AdjstmntDt ISODate `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AdjstmntDt"`
}

// May be one of DAYS, MNTH, WEEK, YEAR
type RateBasis1Code string

type ReconciliationFlag2 struct {
	RptTp            TradeRepositoryReportingType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RptTp,omitempty"`
	BothCtrPtiesRptg bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BothCtrPtiesRptg,omitempty"`
	PairdSts         bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PairdSts,omitempty"`
	LnRcncltnSts     bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LnRcncltnSts,omitempty"`
	CollRcncltnSts   bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollRcncltnSts,omitempty"`
	ModSts           bool                              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ModSts,omitempty"`
}

// May be one of EGRN, EGAE, ETSB, NOAP
type RepoTerminationOption2Code string

// May be one of NOTX
type ReportPeriodActivity1Code string

type SecuritiesFinancingReportingTransactionStateReportV02 struct {
	TradData    TradeStateReport5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TradData"`
	SplmtryData []SupplementaryData1    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SplmtryData,omitempty"`
}

type SecuritiesLendingType3Choice struct {
	Cd    ExternalSecuritiesLendingType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Cd,omitempty"`
	Prtry Max35Text                          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Prtry,omitempty"`
}

type SecuritiesTransactionPrice18Choice struct {
	MntryVal AmountAndDirection107 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MntryVal,omitempty"`
	Pctg     float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Pctg,omitempty"`
	Dcml     float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dcml,omitempty"`
	BsisPts  float64               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BsisPts,omitempty"`
}

type SecuritiesTransactionPrice19Choice struct {
	MntryVal AmountAndDirection107       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MntryVal,omitempty"`
	Unit     float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Unit,omitempty"`
	Pctg     float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Pctg,omitempty"`
	Yld      float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Yld,omitempty"`
	Dcml     float64                     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Dcml,omitempty"`
	PdgPric  PriceStatus1Code            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PdgPric,omitempty"`
	Othr     SecuritiesTransactionPrice5 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Othr,omitempty"`
}

type SecuritiesTransactionPrice5 struct {
	Val float64   `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Val,omitempty"`
	Tp  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp,omitempty"`
}

type Security51 struct {
	Id                ISINOct2015Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	ClssfctnTp        CFIOct2015Identifier               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClssfctnTp,omitempty"`
	QtyOrNmnlVal      QuantityNominalValue2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 QtyOrNmnlVal,omitempty"`
	UnitPric          SecuritiesTransactionPrice19Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitPric,omitempty"`
	MktVal            AmountAndDirection53               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MktVal,omitempty"`
	Qlty              CollateralQualityType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Qlty,omitempty"`
	Mtrty             ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Mtrty,omitempty"`
	Issr              SecurityIssuer4                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Issr,omitempty"`
	Tp                []SecuritiesLendingType3Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp,omitempty"`
	ExclsvArrgmnt     bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExclsvArrgmnt,omitempty"`
	AvlblForCollReuse bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AvlblForCollReuse,omitempty"`
}

type Security52 struct {
	Id                ISINOct2015Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	ClssfctnTp        CFIOct2015Identifier               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClssfctnTp,omitempty"`
	QtyOrNmnlVal      QuantityNominalValue2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 QtyOrNmnlVal,omitempty"`
	UnitPric          SecuritiesTransactionPrice19Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitPric,omitempty"`
	MktVal            AmountAndDirection53               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MktVal,omitempty"`
	Qlty              CollateralQualityType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Qlty,omitempty"`
	Mtrty             ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Mtrty,omitempty"`
	Issr              SecurityIssuer4                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Issr,omitempty"`
	Tp                []SecuritiesLendingType3Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp,omitempty"`
	ExclsvArrgmnt     bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExclsvArrgmnt,omitempty"`
	HrcutOrMrgn       float64                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 HrcutOrMrgn,omitempty"`
	AvlblForCollReuse bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AvlblForCollReuse,omitempty"`
}

type Security55 struct {
	Id                ISINOct2015Identifier              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	ClssfctnTp        CFIOct2015Identifier               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClssfctnTp,omitempty"`
	QtyOrNmnlVal      QuantityNominalValue2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 QtyOrNmnlVal,omitempty"`
	UnitPric          SecuritiesTransactionPrice19Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 UnitPric,omitempty"`
	MktVal            AmountAndDirection53               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MktVal,omitempty"`
	Qlty              CollateralQualityType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Qlty,omitempty"`
	Mtrty             ISODate                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Mtrty,omitempty"`
	Issr              SecurityIssuer4                    `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Issr,omitempty"`
	Tp                []SecuritiesLendingType3Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Tp,omitempty"`
	ExclsvArrgmnt     bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ExclsvArrgmnt,omitempty"`
	AvlblForCollReuse bool                               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AvlblForCollReuse,omitempty"`
	HrcutOrMrgn       float64                            `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 HrcutOrMrgn,omitempty"`
}

type SecurityCommodity9 struct {
	Scty   []Security51  `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Scty,omitempty"`
	Cmmdty []Commodity43 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Cmmdty,omitempty"`
}

type SecurityIdentification26Choice struct {
	Id       ISINOct2015Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	NotAvlbl NotAvailable1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 NotAvlbl,omitempty"`
}

type SecurityIssuer4 struct {
	Id           OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Id,omitempty"`
	JursdctnCtry CountryCode                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 JursdctnCtry"`
}

type SettlementParties34Choice struct {
	CntrlSctiesDpstryPtcpt OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CntrlSctiesDpstryPtcpt,omitempty"`
	IndrctPtcpt            OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 IndrctPtcpt,omitempty"`
}

// May be one of GENE, SPEC
type SpecialCollateral1Code string

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

// May be one of SWOS, TWOS
type TradeRepositoryReportingType1Code string

type TradeStateReport16 struct {
	TechRcrdId      Max140Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TechRcrdId,omitempty"`
	CtrPtySpcfcData CounterpartyData88                `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CtrPtySpcfcData"`
	LnData          TransactionLoanData31Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 LnData,omitempty"`
	CollData        TransactionCollateralData18Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CollData,omitempty"`
	RcncltnFlg      ReconciliationFlag2               `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RcncltnFlg,omitempty"`
	CtrctMod        ContractModification3             `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 CtrctMod"`
	SplmtryData     []SupplementaryData1              `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SplmtryData,omitempty"`
}

type TradeStateReport5Choice struct {
	DataSetActn ReportPeriodActivity1Code `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 DataSetActn,omitempty"`
	Stat        []TradeStateReport16      `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Stat,omitempty"`
}

type TransactionCollateralData18Choice struct {
	RpTrad     Collateral52           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RpTrad,omitempty"`
	BuySellBck Collateral52           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BuySellBck,omitempty"`
	SctiesLndg CollateralFlag13Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SctiesLndg,omitempty"`
	MrgnLndg   []Security55           `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MrgnLndg,omitempty"`
}

type TransactionCounterpartyData11 struct {
	Bnfcry     PartyIdentification236Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Bnfcry,omitempty"`
	TrptyAgt   OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 TrptyAgt,omitempty"`
	Brkr       OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 Brkr,omitempty"`
	ClrMmb     OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 ClrMmb,omitempty"`
	SttlmPties SettlementParties34Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SttlmPties,omitempty"`
	AgtLndr    OrganisationIdentification15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 AgtLndr,omitempty"`
}

type TransactionLoanData31Choice struct {
	RpTrad     LoanData139 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 RpTrad,omitempty"`
	BuySellBck LoanData140 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 BuySellBck,omitempty"`
	SctiesLndg LoanData141 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 SctiesLndg,omitempty"`
	MrgnLndg   LoanData142 `xml:"urn:iso:std:iso:20022:tech:xsd:auth.079.001.02 MrgnLndg,omitempty"`
}

// May be one of REUU, COLU, CORR, ETRM, VALU, POSC, NEWT, MODI, MARU, EROR
type TransactionOperationType6Code string

// May be one of ALOW, ACCY, BARL, BCUF, BDFT, BUSL, CEER, CLRT, KILO, PIEC, TONS, METR, INCH, YARD, GBGA, GRAM, CMET, SMET, FOOT, MILE, SQIN, SQFO, SQMI, GBOU, USOU, GBPI, USPI, GBQA, USGA, MMET, KMET, SQYA, ACRE, ARES, SMIL, SCMT, HECT, SQKI, MILI, CELI, LITR, PUND, CBME, DAYS, DMET, ENVC, ENVO, HUWG, KWDC, KWHO, KWHC, KMOC, KWMC, KWYC, MWDC, MWHO, MWHC, MWMC, MMOC, MWYC, TONE, MIBA, MBTU, OZTR, UCWT, IPNT, PWRD, DGEU, TOCD, GGEU, USQA
type UnitOfMeasure11Code string

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
