// Code generated by download. DO NOT EDIT.

package iso20022_cain_022_001_01

import (
	"bytes"
	"encoding/base64"
	"encoding/xml"
	"time"
)

type AdditionalData1 struct {
	Tp  Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Val Max2048Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Val,omitempty"`
}

type AdditionalFee1 struct {
	Tp         TypeOfAmount10Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp"`
	OthrTp     Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrTp,omitempty"`
	FeePrgm    Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 FeePrgm,omitempty"`
	FeeDscrptr Max35Text          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 FeeDscrptr,omitempty"`
	Amt        FeeAmount2         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Amt"`
	Labl       Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Labl,omitempty"`
}

type AdditionalInformation22 struct {
	Rcpt PartyType19Code      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rcpt,omitempty"`
	Trgt []UserInterface8Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Trgt,omitempty"`
	Frmt OutputFormat4Code    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Frmt,omitempty"`
	Tp   Max35Text            `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Val  Max20KText           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Val"`
}

type Address1 struct {
	AdrLine1       Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AdrLine1,omitempty"`
	AdrLine2       Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AdrLine2,omitempty"`
	StrtNm         Max70Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 StrtNm,omitempty"`
	BldgNb         Max16Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BldgNb,omitempty"`
	PstlCd         Max16Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PstlCd,omitempty"`
	TwnNm          Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TwnNm,omitempty"`
	CtrySubDvsnMnr Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CtrySubDvsnMnr,omitempty"`
	CtrySubDvsnMjr Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CtrySubDvsnMjr,omitempty"`
	Ctry           Min2Max3AlphaText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctry,omitempty"`
}

// May be one of EA2C, E3DC, DKP9, UKPT, UKA1, EA9C, EA5C
type Algorithm13Code string

// May be one of HS25, HS38, HS51
type Algorithm20Code string

// May be one of EA2C, E3DC, EA9C, EA5C, EA2R, EA9R, EA5R, E3DR, E36C, E36R, SD5C
type Algorithm23Code string

// May be one of HS25, HS38, HS51
type Algorithm5Code string

// May be one of ERSA, RSAO
type Algorithm7Code string

// May be one of MGF1
type Algorithm8Code string

type AlgorithmIdentification25 struct {
	Algo  Algorithm23Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo"`
	Param Parameter7      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Param,omitempty"`
}

type AlgorithmIdentification26 struct {
	Algo  Algorithm8Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo"`
	Param Algorithm5Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Param,omitempty"`
}

type AlgorithmIdentification27 struct {
	Algo  Algorithm7Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo"`
	Param Parameter13    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Param,omitempty"`
}

type AlgorithmIdentification28 struct {
	Algo  Algorithm13Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo"`
	Param Parameter14     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Param,omitempty"`
}

// May be one of CNAT, LATT, OATT, OUAT, CATT
type AttributeType1Code string

type BatchManagementInformation1 struct {
	ColltnId         Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ColltnId,omitempty"`
	BtchId           Max35Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BtchId"`
	MsgSeqNb         Max15NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MsgSeqNb,omitempty"`
	MsgChcksmInptVal Max140Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MsgChcksmInptVal,omitempty"`
}

// May be one of LNGT, NUL8, NULG, NULL, RAND
type BytePadding1Code string

type CardData5 struct {
	PAN           Max19NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PAN,omitempty"`
	PrtctdPANInd  bool                `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PrtctdPANInd,omitempty"`
	CardSeqNb     Min2Max3NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardSeqNb,omitempty"`
	PmtAcctRef    Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PmtAcctRef,omitempty"`
	PANAcctRg     Max19NumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PANAcctRg,omitempty"`
	CardPrtflIdr  Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardPrtflIdr,omitempty"`
	AddtlCardData Max70Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlCardData,omitempty"`
}

// May be one of CDFL, ICPY, MGST, ICCY, MICR, MLEY, OCRR, MSIP, OPTC, OTHN, RFID, UNSP, OTHP, KEEN
type CardDataReading7Code string

type CardProgrammeMode1 struct {
	Tp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Id Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
}

type CertificateIssuer1 struct {
	RltvDstngshdNm []RelativeDistinguishedName1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RltvDstngshdNm"`
}

type Contact7 struct {
	Nm     Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Nm,omitempty"`
	FaxNb  PhoneNumber `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 FaxNb,omitempty"`
	TelNb  PhoneNumber `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TelNb,omitempty"`
	Email  Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Email,omitempty"`
	URLAdr Max256Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 URLAdr,omitempty"`
}

type ContentInformationType20 struct {
	MACData MACData1          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MACData"`
	MAC     Max8HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MAC"`
}

// May be one of DATA, SIGN, EVLP, DGST, AUTH
type ContentType2Code string

// May be one of EVLP, IFSE
type ContentType3Code string

type Context4 struct {
	PtOfSvcCntxt PointOfServiceContext2 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PtOfSvcCntxt,omitempty"`
	TxCntxt      TransactionContext3    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TxCntxt"`
	SaleCntxt    SaleContext7           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SaleCntxt,omitempty"`
}

type Credentials1 struct {
	IdCd     Identification2Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 IdCd"`
	OthrIdCd Max35Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrIdCd,omitempty"`
	IdVal    Max70Text           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 IdVal"`
}

type Customer3 struct {
	CstmrId   Max35Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CstmrId,omitempty"`
	Nm        Max70Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Nm,omitempty"`
	Adr       Address1       `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Adr,omitempty"`
	Crdntls   []Credentials1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Crdntls,omitempty"`
	AddtlInf  Max256Text     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlInf,omitempty"`
	DtOfBirth ISODate        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DtOfBirth,omitempty"`
}

type DeliveryInformation2 struct {
	Ctct    Contact7 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctct,omitempty"`
	PstlAdr Address1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PstlAdr,omitempty"`
}

type DisputeIdentification1 struct {
	Tp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Id Max70Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
}

type DisputeReference1 struct {
	AssgnrNtty     PartyType32Code          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AssgnrNtty,omitempty"`
	OthrAssgnrNtty Max35Text                `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrAssgnrNtty,omitempty"`
	DsptId         []DisputeIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DsptId"`
}

type Document struct {
	RtrvlRspn RetrievalResponseV01 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RtrvlRspn"`
}

type ECommerceData1 struct {
	Tp  Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp"`
	Val Max2048Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Val"`
}

type EncryptedContent5 struct {
	CnttTp         ContentType2Code          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CnttTp"`
	CnttNcrptnAlgo AlgorithmIdentification25 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CnttNcrptnAlgo"`
	NcrptdDataElmt []EncryptedDataElement1   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdDataElmt"`
}

type EncryptedData1 struct {
	Ctrl           Exact1HexBinaryText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctrl,omitempty"`
	KeySetIdr      Max8NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeySetIdr,omitempty"`
	DrvdInf        Max32HexBinaryText      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DrvdInf,omitempty"`
	Algo           Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo,omitempty"`
	KeyLngth       Max4NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyLngth,omitempty"`
	KeyPrtcn       Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyPrtcn,omitempty"`
	KeyIndx        Max5NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyIndx,omitempty"`
	PddgMtd        Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PddgMtd,omitempty"`
	NcrptdDataFrmt Max2NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdDataFrmt,omitempty"`
	NcrptdDataElmt []EncryptedDataElement1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdDataElmt"`
}

type EncryptedData1Choice struct {
	BinryData   Max100KBinary `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BinryData,omitempty"`
	HexBinryVal string        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 HexBinryVal,omitempty"`
}

type EncryptedDataElement1 struct {
	Id                   ExternalEncryptedElementIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
	OthrId               Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrId,omitempty"`
	NcrptdData           EncryptedData1Choice                        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdData"`
	ClearTxtDataFrmt     EncryptedDataFormat1Code                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ClearTxtDataFrmt,omitempty"`
	OthrClearTxtDataFrmt Max35Text                                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrClearTxtDataFrmt,omitempty"`
}

// May be one of ASCI, BINF, EBCD, HEXF, OTHN, OTHP
type EncryptedDataFormat1Code string

// May be one of TR34, TR31, CTCE, CBCE
type EncryptionFormat3Code string

type EnvelopedData6 struct {
	Vrsn       float64            `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Vrsn,omitempty"`
	Rcpt       []Recipient7Choice `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rcpt"`
	NcrptdCntt EncryptedContent5  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdCntt,omitempty"`
}

type Environment13 struct {
	Acqrr  PartyIdentification197 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Acqrr"`
	Sndr   PartyIdentification197 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Sndr,omitempty"`
	Rcvr   PartyIdentification197 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rcvr,omitempty"`
	Accptr PartyIdentification203 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Accptr,omitempty"`
	Pyer   PartyIdentification211 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Pyer,omitempty"`
	Pyee   PartyIdentification211 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Pyee,omitempty"`
	Termnl Terminal2              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Termnl,omitempty"`
	Card   CardData5              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Card"`
	Wllt   Wallet1                `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Wllt,omitempty"`
	Tkn    Token1                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tkn,omitempty"`
}

// Must match the pattern ([0-9A-F][0-9A-F]){1}
type Exact1HexBinaryText string

// Must match the pattern [a-zA-Z0-9]{2}
type Exact2AlphaNumericText string

// Must match the pattern [0-9]{2}
type Exact2NumericText string

// Must match the pattern [0-9]{4}
type Exact4NumericText string

// Must match the pattern ([0-9A-F][0-9A-F]){1,3}
type ExternalEncryptedElementIdentification1Code string

type FeeAmount2 struct {
	Amt      float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Amt"`
	Ccy      ISO3NumericCurrencyCode `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ccy,omitempty"`
	XchgRate float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 XchgRate,omitempty"`
	QtnDt    ISODateTime             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 QtnDt,omitempty"`
	Sgn      bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Sgn,omitempty"`
}

type FinancialInstitution4 struct {
	Id           Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
	Nm           Max70Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Nm,omitempty"`
	Adr          Address1   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Adr,omitempty"`
	Email        Max256Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Email,omitempty"`
	URLAdr       Max256Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 URLAdr,omitempty"`
	PhneNb       Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PhneNb,omitempty"`
	CstmrSvc     Max35Text  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CstmrSvc,omitempty"`
	AddtlCtctInf Max256Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlCtctInf,omitempty"`
}

type GenericIdentification172 struct {
	Id     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	Tp     PartyType17Code   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	OthrTp Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrTp,omitempty"`
	Assgnr PartyType18Code   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Assgnr,omitempty"`
	Ctry   Min2Max3AlphaText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctry,omitempty"`
	ShrtNm Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ShrtNm,omitempty"`
}

// May be one of ELEC, PHYS, ELPH
type GoodsAndServices1Code string

// May be one of CRCU, FORX, OTHN, OTHP, SECS
type GoodsAndServicesSubType1Code string

type Header55 struct {
	MsgFctn        MessageFunction37Code       `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MsgFctn"`
	PrtcolVrsn     Max2048Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PrtcolVrsn"`
	XchgId         Max35Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 XchgId,omitempty"`
	ReTrnsmssnCntr Max3NumericText             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ReTrnsmssnCntr,omitempty"`
	CreDtTm        ISODateTime                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CreDtTm"`
	BtchMgmtInf    BatchManagementInformation1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BtchMgmtInf,omitempty"`
	InitgPty       GenericIdentification172    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 InitgPty"`
	RcptPty        GenericIdentification172    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RcptPty,omitempty"`
	TracData       []AdditionalData1           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TracData,omitempty"`
	Tracblt        []Traceability7             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tracblt,omitempty"`
}

// Must match the pattern [0-9]{3,3}
type ISO3NumericCountryCode string

// Must match the pattern [0-9]{3,3}
type ISO3NumericCurrencyCode string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type ISOTime time.Time

func (t *ISOTime) UnmarshalText(text []byte) error {
	return (*xsdTime)(t).UnmarshalText(text)
}
func (t ISOTime) MarshalText() ([]byte, error) {
	return xsdTime(t).MarshalText()
}

// May be one of DRID, NTID, PASS, SSYN, ARNB, OTHP, OTHN, EMAL, PHNB
type Identification2Code string

type IssuerAndSerialNumber1 struct {
	Issr  CertificateIssuer1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Issr"`
	SrlNb Max35Binary        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SrlNb"`
}

type KEK6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Vrsn,omitempty"`
	KEKId         KEKIdentifier6            `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KEKId"`
	KeyNcrptnAlgo AlgorithmIdentification28 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyNcrptnAlgo"`
	NcrptdKey     Max500Binary              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdKey,omitempty"`
}

type KEKIdentifier2 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyVrsn"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DerivtnId,omitempty"`
}

type KEKIdentifier6 struct {
	KeyId     Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyId"`
	KeyVrsn   Max140Text      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyVrsn,omitempty"`
	SeqNb     float64         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SeqNb,omitempty"`
	DerivtnId Min5Max16Binary `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DerivtnId,omitempty"`
}

type KeyTransport6 struct {
	Vrsn          float64                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Vrsn,omitempty"`
	RcptId        Recipient5Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RcptId"`
	KeyNcrptnAlgo AlgorithmIdentification27 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyNcrptnAlgo"`
	NcrptdKey     Max5000Binary             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdKey"`
}

type MACData1 struct {
	Ctrl         Exact1HexBinaryText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctrl"`
	KeySetIdr    Max8NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeySetIdr"`
	DrvdInf      Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DrvdInf,omitempty"`
	Algo         Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Algo"`
	KeyLngth     Max4NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyLngth,omitempty"`
	KeyPrtcn     Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyPrtcn,omitempty"`
	KeyIndx      Max5NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyIndx,omitempty"`
	PddgMtd      Max2NumericText     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PddgMtd,omitempty"`
	InitlstnVctr Max32HexBinaryText  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 InitlstnVctr,omitempty"`
}

// May be no more than 1000 items long
type Max1000Text string

type Max100KBinary []byte

func (t *Max100KBinary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max100KBinary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,11}
type Max11NumericText string

// Must match the pattern [0-9]{1,12}
type Max12NumericText string

type Max140Binary []byte

func (t *Max140Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max140Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be no more than 140 items long
type Max140Text string

// Must match the pattern [0-9]{1,15}
type Max15NumericText string

// May be no more than 16 items long
type Max16Text string

// Must match the pattern [0-9]{1,19}
type Max19NumericText string

// May be no more than 2048 items long
type Max2048Text string

// May be no more than 20000 items long
type Max20KText string

// Must match the pattern [0-9]{1,23}
type Max23NumericText string

// May be no more than 256 items long
type Max256Text string

// Must match the pattern [0-9]{1,2}
type Max2NumericText string

// Must match the pattern ([0-9A-F][0-9A-F]){1,32}
type Max32HexBinaryText string

// May be no more than 350 items long
type Max350Text string

type Max35Binary []byte

func (t *Max35Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max35Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,35}
type Max35NumericText string

// May be no more than 35 items long
type Max35Text string

// Must match the pattern [0-9]{1,3}
type Max3NumericText string

// Must match the pattern [0-9]{1,4}
type Max4NumericText string

type Max5000Binary []byte

func (t *Max5000Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max5000Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

type Max500Binary []byte

func (t *Max500Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Max500Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// Must match the pattern [0-9]{1,5}
type Max5NumericText string

// May be no more than 70 items long
type Max70Text string

// Must match the pattern ([0-9A-F][0-9A-F]){1,8}
type Max8HexBinaryText string

// Must match the pattern [0-9]{1,8}
type Max8NumericText string

// May be no more than 99 items long
type Max99Text string

// May be one of ADVC, NOTI, REQU, STNO, STRQ, STAD
type MessageFunction37Code string

// Must match the pattern [a-zA-Z]{2,3}
type Min2Max3AlphaText string

// Must match the pattern [0-9]{2,3}
type Min2Max3NumericText string

type Min5Max16Binary []byte

func (t *Min5Max16Binary) UnmarshalText(text []byte) error {
	return (*xsdBase64Binary)(t).UnmarshalText(text)
}
func (t Min5Max16Binary) MarshalText() ([]byte, error) {
	return xsdBase64Binary(t).MarshalText()
}

// May be one of FLNM, MREF, OTHN, OTHP, SMSI, TEXT, URLI, HTML
type OutputFormat4Code string

type Parameter13 struct {
	DgstAlgo     Algorithm20Code           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DgstAlgo,omitempty"`
	MskGnrtrAlgo AlgorithmIdentification26 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MskGnrtrAlgo,omitempty"`
}

type Parameter14 struct {
	NcrptnFrmt   EncryptionFormat3Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptnFrmt,omitempty"`
	InitlstnVctr Max500Binary          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BPddg,omitempty"`
}

type Parameter7 struct {
	InitlstnVctr Max500Binary     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 InitlstnVctr,omitempty"`
	BPddg        BytePadding1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 BPddg,omitempty"`
}

type PartyIdentification197 struct {
	Id      Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	Assgnr  Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Assgnr,omitempty"`
	Ctry    ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctry,omitempty"`
	ShrtNm  Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ShrtNm,omitempty"`
	AddtlId Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlId,omitempty"`
}

type PartyIdentification203 struct {
	Id           Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	Assgnr       Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Assgnr,omitempty"`
	Ctry         ISO3NumericCountryCode `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctry,omitempty"`
	ShrtNm       Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ShrtNm,omitempty"`
	AddtlId      Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlId,omitempty"`
	NmAndLctn    Max99Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NmAndLctn"`
	Adr          Address1               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Adr,omitempty"`
	Email        Max256Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Email,omitempty"`
	URLAdr       Max256Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 URLAdr,omitempty"`
	PhneNb       Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PhneNb,omitempty"`
	CstmrSvc     Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CstmrSvc,omitempty"`
	AddtlCtctInf Max256Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlCtctInf,omitempty"`
	TaxRegnId    Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TaxRegnId,omitempty"`
	AddtlData    []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlData,omitempty"`
	SpnsrdMrchnt []SponsoredMerchant1   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SpnsrdMrchnt,omitempty"`
}

type PartyIdentification211 struct {
	FI    FinancialInstitution4 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 FI,omitempty"`
	Cstmr Customer3             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Cstmr,omitempty"`
}

// May be one of OTHN, OTHP, ACQR, ACQP, CISS, CISP, AGNT
type PartyType17Code string

// May be one of ACQR, CISS, CSCH, AGNT
type PartyType18Code string

// May be one of ACCP, ACQR, ACQP, CISS, CISP, AGNT, OTHN, OTHP
type PartyType19Code string

// May be one of ACQR, AGNT, ISUR, OTHN, OTHP
type PartyType32Code string

// Must match the pattern \+[0-9]{1,3}-[0-9()+\-]{1,30}
type PhoneNumber string

type PointOfServiceContext2 struct {
	CardPres           bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardPres,omitempty"`
	CrdhldrPres        bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CrdhldrPres,omitempty"`
	CrdhldrActvtd      bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CrdhldrActvtd,omitempty"`
	TrnspndrInittd     bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TrnspndrInittd,omitempty"`
	AttnddInd          bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AttnddInd,omitempty"`
	UattnddLvlCtgy     Max35NumericText               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 UattnddLvlCtgy,omitempty"`
	EComrcInd          bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 EComrcInd,omitempty"`
	EComrcData         []ECommerceData1               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 EComrcData,omitempty"`
	MOTOInd            bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MOTOInd,omitempty"`
	PrtlApprvlSpprtd   bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PrtlApprvlSpprtd,omitempty"`
	DelydAuthstnInd    bool                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DelydAuthstnInd,omitempty"`
	SctyChrtcs         []SecurityCharacteristics1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SctyChrtcs,omitempty"`
	OthrSctyChrtcs     Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrSctyChrtcs,omitempty"`
	CardDataNtryMd     CardDataReading7Code           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardDataNtryMd,omitempty"`
	OthrCardDataNtryMd Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrCardDataNtryMd,omitempty"`
	StorgLctn          Max35Text                      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 StorgLctn,omitempty"`
	SpclConds          []SpecialConditions1           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SpclConds,omitempty"`
}

// May be one of URGT, HIGH, NORM
type Priority3Code string

type ProcessingResult4 struct {
	RsltData      ResultData5               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RsltData,omitempty"`
	OrgnlRsltData ResultData1               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OrgnlRsltData,omitempty"`
	AddtlInf      []AdditionalInformation22 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlInf,omitempty"`
}

type ProtectedData1 struct {
	CnttTp     ContentType3Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CnttTp"`
	EnvlpdData EnvelopedData6   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 EnvlpdData,omitempty"`
	NcrptdData EncryptedData1   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 NcrptdData,omitempty"`
}

// May be one of EMAL, OTHR, PAPR, SMSM, URID
type ReceiptType1Code string

type Recipient5Choice struct {
	IssrAndSrlNb IssuerAndSerialNumber1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 IssrAndSrlNb,omitempty"`
	KeyIdr       KEKIdentifier2         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyIdr,omitempty"`
}

type Recipient7Choice struct {
	KeyTrnsprt KeyTransport6  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyTrnsprt,omitempty"`
	KEK        KEK6           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KEK,omitempty"`
	KeyIdr     KEKIdentifier6 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 KeyIdr,omitempty"`
}

type Reconciliation3 struct {
	Id        Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
	Dt        ISODate   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Dt,omitempty"`
	ChckptRef Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ChckptRef,omitempty"`
}

type RelativeDistinguishedName1 struct {
	AttrTp  AttributeType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AttrTp"`
	AttrVal Max140Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AttrVal"`
}

// May be one of PRCS, UNPR, UNRV, REJT, TECH, OTHN, OTHP
type Response8Code string

type ResultData1 struct {
	Rslt         Response8Code          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rslt,omitempty"`
	OthrRslt     Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrRslt,omitempty"`
	RsltDtls     Exact2AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RsltDtls"`
	OthrRsltDtls Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrRsltDtls,omitempty"`
	AddtlRsltInf []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlRsltInf,omitempty"`
}

type ResultData5 struct {
	Rslt         Response8Code          `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rslt,omitempty"`
	OthrRslt     Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 OthrRslt,omitempty"`
	RsltDtls     Exact2AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RsltDtls"`
	AddtlRsltInf []AdditionalData1      `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlRsltInf,omitempty"`
}

type RetrievalDeliveryMethod1Choice struct {
	ReqdMtd      []Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ReqdMtd,omitempty"`
	EstblishdMtd []Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 EstblishdMtd,omitempty"`
	ActlDlvryMtd Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ActlDlvryMtd,omitempty"`
}

type RetrievalFulfilmentInstructions1 struct {
	Mtd      RetrievalDeliveryMethod1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Mtd,omitempty"`
	DlvryInf DeliveryInformation2           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DlvryInf,omitempty"`
	AddtlInf AdditionalInformation22        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlInf,omitempty"`
}

type RetrievalResponse1 struct {
	Envt        Environment13        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Envt"`
	Cntxt       Context4             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Cntxt,omitempty"`
	Tx          Transaction89        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tx,omitempty"`
	PrcgRslt    ProcessingResult4    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PrcgRslt"`
	PrtctdData  []ProtectedData1     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PrtctdData,omitempty"`
	SplmtryData []SupplementaryData1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SplmtryData,omitempty"`
}

type RetrievalResponseV01 struct {
	Hdr      Header55                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Hdr"`
	Body     RetrievalResponse1       `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Body"`
	SctyTrlr ContentInformationType20 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SctyTrlr,omitempty"`
}

type SaleContext7 struct {
	SaleId               Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SaleId,omitempty"`
	SaleRefId            Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SaleRefId,omitempty"`
	SaleRefNb            Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SaleRefNb,omitempty"`
	GoodsAndSvcsTp       GoodsAndServices1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 GoodsAndSvcsTp,omitempty"`
	GoodAndSvcsSubTp     GoodsAndServicesSubType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 GoodAndSvcsSubTp,omitempty"`
	GoodAndSvcsOthrSubTp Max35Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 GoodAndSvcsOthrSubTp,omitempty"`
	SpltPmtInd           bool                         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SpltPmtInd,omitempty"`
	RctReqInd            bool                         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RctReqInd,omitempty"`
	RctTp                []ReceiptType1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RctTp,omitempty"`
	RctDstn              Max70Text                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RctDstn,omitempty"`
}

// May be one of CETE, CPTE, CENC, CMAC, ETEE, METE, MPTE, OPNN, PMAC, PKIE, PRAE, PRAM, PRVN, STAM, APTE, AETE, OTHN, OTHP
type SecurityCharacteristics1Code string

type SettlementReportingEntity1 struct {
	Tp Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Id Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
}

type SettlementService2 struct {
	SttlmSvcApld  SettlementServiceMode1     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmSvcApld,omitempty"`
	SttlmSvcDts   SettlementServiceDate1     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmSvcDts,omitempty"`
	SttlmRptgNtty SettlementReportingEntity1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmRptgNtty,omitempty"`
}

type SettlementServiceDate1 struct {
	ReqdSttlmDt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ReqdSttlmDt,omitempty"`
	SttlmDt       ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmDt,omitempty"`
	SttlmTm       ISOTime     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmTm,omitempty"`
	SttlmPrd      Max35Text   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmPrd,omitempty"`
	SttlmCutOffTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmCutOffTm,omitempty"`
}

type SettlementServiceMode1 struct {
	Tp        Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Tp,omitempty"`
	Id        Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
	ShrtNm    Max35Text     `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ShrtNm,omitempty"`
	SttlmPrty Priority3Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmPrty,omitempty"`
}

type SpecialConditions1 struct {
	Id  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id,omitempty"`
	Val Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Val,omitempty"`
}

type SpecialProgrammeDetails1 struct {
	Nm  Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Nm,omitempty"`
	Val Max35Text `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Val,omitempty"`
}

type SpecialProgrammeQualification1 struct {
	Prgrmm Max35Text                  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Prgrmm,omitempty"`
	Dtl    []SpecialProgrammeDetails1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Dtl,omitempty"`
}

type SponsoredMerchant1 struct {
	Id      PartyIdentification197 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	AddtlId Max35Text              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlId,omitempty"`
	CmonNm  Max140Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CmonNm,omitempty"`
	Adr     Address1               `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Adr,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type Terminal2 struct {
	TermnlId TerminalIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TermnlId"`
}

type TerminalIdentification1 struct {
	Id     Max16Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	Assgnr Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Assgnr,omitempty"`
	Ctry   Min2Max3AlphaText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Ctry,omitempty"`
	ShrtNm Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 ShrtNm,omitempty"`
}

type Token1 struct {
	PmtTkn        Max19NumericText  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PmtTkn,omitempty"`
	TknXpryDt     Exact4NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TknXpryDt,omitempty"`
	TknRqstrId    Max11NumericText  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TknRqstrId,omitempty"`
	TknAssrncData Max140Text        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TknAssrncData,omitempty"`
	TknAssrncMtd  Max2NumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TknAssrncMtd,omitempty"`
	TknInittdInd  bool              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TknInittdInd,omitempty"`
}

type Traceability7 struct {
	RlayId      GenericIdentification172 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RlayId"`
	TracDtTmIn  ISODateTime              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TracDtTmIn,omitempty"`
	TracDtTmOut ISODateTime              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TracDtTmOut,omitempty"`
}

type Transaction89 struct {
	MsgRsn           []Exact4NumericText                `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MsgRsn,omitempty"`
	AltrnMsgRsn      []Max35Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AltrnMsgRsn,omitempty"`
	SpclPrgrmmQlfctn []SpecialProgrammeQualification1   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SpclPrgrmmQlfctn,omitempty"`
	TxId             TransactionIdentification11        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TxId"`
	DsptRef          []DisputeReference1                `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 DsptRef,omitempty"`
	RtrvlFlfmtInstrs []RetrievalFulfilmentInstructions1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RtrvlFlfmtInstrs,omitempty"`
	AddtlFees        []AdditionalFee1                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlFees,omitempty"`
	TxDesc           Max1000Text                        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TxDesc,omitempty"`
	AddtlData        []AdditionalData1                  `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlData,omitempty"`
}

type TransactionContext3 struct {
	MrchntCtgyCd   Exact4NumericText         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 MrchntCtgyCd,omitempty"`
	TxInitr        TransactionInitiator1Code `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TxInitr,omitempty"`
	CardPrgrmmApld CardProgrammeMode1        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardPrgrmmApld,omitempty"`
	SttlmSvc       SettlementService2        `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SttlmSvc,omitempty"`
	Rcncltn        Reconciliation3           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Rcncltn,omitempty"`
}

type TransactionIdentification11 struct {
	LclDtTm             ISODateTime                         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 LclDtTm,omitempty"`
	TmZone              Max70Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TmZone,omitempty"`
	TxRef               Max35Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TxRef,omitempty"`
	TrnsmssnDtTm        ISODateTime                         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 TrnsmssnDtTm,omitempty"`
	SysTracAudtNb       Max12NumericText                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 SysTracAudtNb"`
	RtrvlRefNb          string                              `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 RtrvlRefNb"`
	LifeCyclSpprtInd    Exact2NumericText                   `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 LifeCyclSpprtInd,omitempty"`
	LifeCyclTracIdData  TransactionLifeCycleIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 LifeCyclTracIdData,omitempty"`
	LifeCyclTracIdMssng Max70Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 LifeCyclTracIdMssng,omitempty"`
	AcqrrRefData        Max99Text                           `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AcqrrRefData,omitempty"`
	AcqrrRefNb          Max23NumericText                    `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AcqrrRefNb,omitempty"`
	CardIssrRefData     Max1000Text                         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 CardIssrRefData,omitempty"`
}

// May be one of MERC, CUST
type TransactionInitiator1Code string

type TransactionLifeCycleIdentification1 struct {
	Id              string            `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Id"`
	AuthstnSeqNb    Exact2NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AuthstnSeqNb,omitempty"`
	PresntmntSeqNb  Exact2NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PresntmntSeqNb,omitempty"`
	PresntmntSeqCnt Exact2NumericText `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 PresntmntSeqCnt,omitempty"`
	AuthntcnTkn     Max35Text         `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AuthntcnTkn,omitempty"`
}

// May be one of INTC, FEEP, OTHN, OTHP, FEEA
type TypeOfAmount10Code string

// May be one of DSPU, FILE, LOGF, OTHP, OTHN
type UserInterface8Code string

type Wallet1 struct {
	Prvdr         PartyIdentification197 `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 Prvdr,omitempty"`
	AddtlWlltData Max256Text             `xml:"urn:iso:std:iso:20022:tech:xsd:cain.022.001.01 AddtlWlltData,omitempty"`
}

type xsdBase64Binary []byte

func (b *xsdBase64Binary) UnmarshalText(text []byte) (err error) {
	*b, err = base64.StdEncoding.DecodeString(string(text))
	return
}
func (b xsdBase64Binary) MarshalText() ([]byte, error) {
	var buf bytes.Buffer
	enc := base64.NewEncoder(base64.StdEncoding, &buf)
	enc.Write([]byte(b))
	enc.Close()
	return buf.Bytes(), nil
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}

type xsdTime time.Time

func (t *xsdTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "15:04:05.999999999")
}
func (t xsdTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
